const actions = {
  REQUEST_AUTHENTICATION: 'REQUEST_AUTHENTICATION',

  GET_STATE: 'GET_STATE',
  GET_CONFIG: 'GET_CONFIG',
  RESET_CONFIG: 'RESET_CONFIG',
  SAVE_CONFIG: 'SAVE_CONFIG',

  SET_LOADING_NEW_TRACK: 'SET_LOADING_NEW_TRACK',
  SET_TRACK_PLAYING: 'SET_TRACK_PLAYING',
  SET_PLAY_STATE: 'SET_PLAY_STATE',
  SET_PLAY_TIME: 'SET_PLAY_TIME',

  TOGGLE_DISABLE_SCROBBLE_CURRENT: 'TOGGLE_DISABLE_SCROBBLE_CURRENT',
}

export default actions
