const scrobbleStates = {
  NO_CONNECTOR: 'NO_CONNECTOR' as const,
  SEARCHING: 'SEARCHING' as const,
  SCROBBLED: 'SCROBBLED' as const,
  WILL_SCROBBLE: 'WILL_SCROBBLE' as const,
  FORCE_SCROBBLE: 'FORCE_SCROBBLE' as const,
  TRACK_NOT_RECOGNISED: 'TRACK_NOT_RECOGNISED' as const,
  BELOW_MIN_SCROBBLER_QUALITY: 'BELOW_MIN_SCROBBLER_QUALITY' as const,
  TRACK_TOO_SHORT: 'TRACK_TOO_SHORT' as const,
  BLOCKED_BY_CONNECTOR: 'BLOCKED_BY_CONNECTOR' as const,
  MANUALLY_DISABLED: 'MANUALLY_DISABLED' as const,
  BLOCKED_BY_BEING_PRIVATE: 'BLOCKED_BY_BEING_PRIVATE' as const,
}

export default scrobbleStates
